---

- hosts: all
  sudo: yes
  roles:
    - franklinkim.apt
  vars:
    apt_cache_valid_time: 7200
    apt_packages:
      - vim
      - tree
    apt_mails:
      - root
    apt_unattended_upgrades_notify_always: yes

