---

- name: Removing packages that are no longer needed for dependencies
  shell: >
    apt-get -y autoremove
  when: apt_autoremove and (apt_upgrade_result.changed or apt_packages_result.changed)

- name: Removing .deb files for packages no longer on your system
  shell: >
    apt-get -y autoclean
  when: apt_autoclean and (apt_upgrade_result.changed or apt_packages_result.changed)
