---
- name: Configure deb822 repository
  become: true
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: "{{ item.type | default('deb') }}"
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_deb822_repositories }}"
  register: deb822_repo
