---

- name: Updating cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - system
    - apt

- name: Upgrading packages
  apt:
    upgrade: "{{ apt_upgrade }}"
  tags:
    - system
    - apt

- name: Installing packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: apt_packages
  tags:
    - system
    - apt
