---

- include: config.yml
  tags:
    - system
    - apt
    - config
    - apt-config

- include: install.yml
  tags:
    - system
    - apt
    - install
    - apt-install

- include: manage.yml
  tags:
    - system
    - apt
    - manage
    - apt-manage
