---

- name: Updating cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - system
    - apt

- name: Upgrading packages
  apt:
    upgrade: yes
  tags:
    - system
    - apt

- name: Installing default packages
  apt:
    pkg: python-apt
    state: latest
  tags:
    - system
    - apt

- name: Installing additional packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: apt_packages
  when: apt_packages is defined
  tags:
    - system
    - apt
