---

- name: Ensuring packages
  apt:
    name: "{{ (apt_package is mapping)|ternary(apt_package.name, apt_package) }}"
    state: "{{ apt_package.state|default(apt_package_state) }}"
    default_release: "{{ apt_package.default_release|default(omit) }}"
    force: "{{ apt_package.force|default(omit) }}"
    only_upgrade: "{{ apt_package.only_upgrade|default(omit) }}"
    install_recommends: "{{ apt_package.install_recommends|default(apt_install_recommends) }}"
    autoremove: "{{ apt_autoremove }}"
    purge: "{{ apt_package.purge|default(omit) }}"
  with_items: "{{ apt_packages }}"
  loop_control:
    loop_var: apt_package
