---

- name: Creating Download timer directory
  file:
    path: "etc/systemd/system/apt-daily.timer.d"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: apt_unattended_upgrades_download_timer_override | bool

- name: Configuring Download timer
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: apt_unattended_upgrades_download_timer_override | bool
  with_items:
    - "etc/systemd/system/apt-daily.timer.d/override.conf"
  notify: Reloading APT timer

- name: Creating Upgrade timer directory
  file:
    path: "etc/systemd/system/apt-daily-upgrade.timer.d"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: apt_unattended_upgrades_upgrade_timer_override | bool

- name: Configuring Upgrade timer
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: apt_unattended_upgrades_upgrade_timer_override | bool
  with_items:
    - "etc/systemd/system/apt-daily-upgrade.timer.d/override.conf"
  notify: Reloading APT timer

